name: Keep Alive
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:  # Allows manual triggering
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          set -o nounset
          set -o errexit
          set -o pipefail
          if [ "${TRACE-0}" -eq 1 ]; then set -o xtrace; fi
    
          readonly COMMIT_USER_NAME="GitHub Action - Workflow keepalive"
          readonly COMMIT_USER_EMAIL="github-action-keepalive-bot@github.com"
          readonly TIME_ELAPSED_THRESHOLD_IN_DAYS=50
          readonly COMMIT_MESSAGE="GitHub Action - Workflow keepalive"
    
          git --version
          git config user.name "$COMMIT_USER_NAME"
          git config user.email "$COMMIT_USER_EMAIL"
    
          # Get the last commit date for the current branch
          LAST_COMMIT_DATE=$(git log -1 --format="%ct")
    
          CURRENT_DATE=$(date "+%s")
    
          TIME_DIFFERENCE=$((CURRENT_DATE - LAST_COMMIT_DATE))
    
          DAYS_AGO=$((TIME_DIFFERENCE / (60 * 60 * 24)))
    
          echo "Last commit is '$DAYS_AGO' days ago"
    
          if [ "$DAYS_AGO" -gt "$TIME_ELAPSED_THRESHOLD_IN_DAYS" ]; then
            echo "$DAYS_AGO > $TIME_ELAPSED_THRESHOLD_IN_DAYS -> add empty commit"
    
            git commit --allow-empty -m "$COMMIT_MESSAGE"
            git push
    
            echo "done"
          else
            echo "$DAYS_AGO <= $TIME_ELAPSED_THRESHOLD_IN_DAYS -> nothing to do"
          fi
